# -*- coding: utf-8 -*-
"""
Created on Tue Feb  2 09:52:52 2021

@author: Jaime Díez Mérida @LDQM group at ICFO. 

Very basic code to extract the data from the .log files generated by the ICEOxford system. 
It reads the log files, extracts the data and saves it in a new .txt file with the same name. 
The new .txt file is tab-delimited and can be easily read by other programs.
"""
import os
import numpy as np

class Object():
    pass



def read_ICEOxford_log(filepath,filename):
    
    f=open(filepath+'/ICEOxford_lognames.txt','r')
    names=f.read()
    f.close()
    
    f=open(filepath+'/'+filename,'r')
    filedata=f.read()
    f.close()
    
    names=names.replace('\n','\t')
    
    filedata=filedata.replace(':','')
    filedata=filedata.replace('/','')
    filedata=filedata.replace(',','\t')
    filedata=filedata.replace(' ','\t')
    
    filename2=filename.replace('.log','_new.txt')

    
    f=open(filepath+'/'+filename2,'w+')
    f.write(names)
    f.write('\n')
    f.write(filedata)
    f.close()

def parse_data(fname,skiprows=1):
    ### Prepare the data: remove the dots
    with open(fname) as myfile:
        
        head = [next(myfile) for x in range(skiprows)]

        head_names = head[0].replace(' ','')
        head_names = head_names.replace('-','')
        #scan_type=head[2]
        #head_unit = head_names.replace('\n','')
        data = np.loadtxt(fname,delimiter = '\t',skiprows=skiprows)
        names = head_names.split("\t");
    #print(head_names)
    # Parse the data into a class with attributes    
    fdata = Object()  
    for i in range(len(names)-1):

        setattr(fdata, names[i], data[:,i])

        
    return fdata,data,names
 
def logTest(s): return '.log' in s and not '.txt' in s

filepath = os.getcwd()
allFiles=os.listdir(filepath)
exceptFiles=[]

#filename ='TBGTB5_4 probe_13_7_11_9_2K_bias10nA_sen200uV_tconst300ms_mVtgVbg_1.hdf5'
print(filepath)

list = filter(logTest,allFiles)

counter=0
for s in list:
    #sTxt=txtThere(s)
    #exceptFiles.append(sTxt)
    #if exceptFiles[counter] not in allFiles or os.stat(filepath+'/'+ sTxt).st_size==0:
    read_ICEOxford_log(filepath, s)
    counter=counter+1  